---
title: "Greenhouse Gas Emissions"
author: "Tilina"
date: '2022-06-10'
output: html_document
---

```{r echo = FALSE, message = FALSE, warning = FALSE}
# Libraries
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)

# Greenhouse gas emissions by country-year from 1750 - 2020
ghg <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2.csv')

# Greenhouse gas emissions by country-year-sector from 1990 - 2018
sectors <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2_sectors.csv')
```

# Present-Day Patterns in Co2 Emissions

## Entities
Entities with the Highest Co2 Emissions:
```{r echo = FALSE}
#Entity with highest co2
ent <- sectors %>% 
  filter(year >= 2000 
         & entity != 'World' 
         & entity != 'European Union (27)') %>% 
  group_by(entity) %>% 
  summarize(total = sum(co2, na.rm = TRUE)/1000000000) %>% 
  arrange(desc(total)) %>%
  head(10) %>% 
  arrange(total) %>% 
  mutate(entity = factor(entity, levels = entity))

options(scipen = 999)
```

```{r echo = FALSE}
ggplot(data = ent) +
  geom_col(aes(x = entity, y = total, color = entity)) +
  coord_flip() + 
  labs(y = "Total Co2 in Billions", x = "Entity", title = "Entities With Highest Co2 Emissions") + 
  scale_color_hue() +
  theme(legend.position = "none")
```

Entities with the Lowest Co2 Emissions:
```{r echo = FALSE}
#Entity with lowest co2
entLow <- sectors %>% 
  filter(year >= 2000 
         & entity != 'World' 
         & entity != 'European Union (27)') %>% 
  group_by(entity) %>% 
  summarize(total = sum(co2, na.rm = TRUE)/1000000000) %>% 
  arrange(total) %>%
  head(10) %>% 
  arrange(desc(total)) %>% 
  mutate(entity = factor(entity, levels = entity))

options(scipen = 999)
```

```{r echo = FALSE}
ggplot(data = entLow) +
  geom_col(aes(x = entity, y = total, color = entity)) +
  coord_flip() + 
  labs(y = "Total Co2 in Billions", x = "Entity", title = "Entities With Lowest Co2 Emissions") + 
  scale_color_hue() +
  theme(legend.position = "none")
```


## Sectors
Sectors with the Highest and Lowest Co2 Emissions:
```{r echo = FALSE}
#Sector with highest/lowest
sect <- sectors %>% 
  filter(year >= 2000) %>% 
  group_by(sector) %>% 
  summarize(total = sum(co2, na.rm = TRUE)/1000000000) %>% 
  arrange(total) %>%
  mutate(sector = factor(sector, levels = sector))

options(scipen = 999)
```

```{r echo = FALSE}
ggplot(data = sect) +
  geom_col(aes(x = sector, y = total, color = sector)) +
  coord_flip() + 
  labs(y = "Total Co2 in Billions", x = "Sector", title = "Economic Sectors and Their Co2 Emissions") + 
  scale_color_hue() +
  theme(legend.position = "none") 
```



# Long-Term Trends in Carbon Emissions Over Time
Sector-by-Sector:
```{r echo = FALSE}
sect <- sectors %>% 
  group_by(sector, year) %>% 
  summarize(total = sum(co2, na.rm = TRUE)/1000000000) 
```

```{r echo = FALSE}
ggplot(data = sect) + 
  geom_line(aes(x = year, y = total, color = sector)) +
  labs(title = 'Long Term Carbon Emissions by Sector', 
       x = 'Year', y = 'Co2 in Billions')
```

Country-by-Country:
```{r echo = FALSE}
count <- sectors %>% 
  filter(entity == 'China' |
           entity == 'United States' |
           entity == 'India' |
           entity == 'Russia' |
           entity == 'Japan') %>% 
  group_by(entity, year) %>% 
  summarize(total = sum(co2, na.rm = TRUE)/1000000000)

ggplot(data = count) + 
  geom_line(aes(x = year, y = total, color = entity)) +
  labs(title = 'Long Term Carbon Emissions by County', 
       x = 'Year', y = 'Co2 in Billions')
```


